### ISSUE TITLE
container support

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#66]

**Comment by spiermar** [comment]
- [ ] resolve hostname based on container name https://github.com/Netflix/vector/issues/70
- [ ] global container name filter https://github.com/Netflix/vector/issues/71
- [ ] container-specific dashboard https://github.com/Netflix/vector/issues/72
- [ ] container throttling widgets https://github.com/Netflix/vector/issues/73

**Comment by spiermar** [comment]
Changes are being made under the "container" branch. https://github.com/Netflix/vector/tree/container

**Comment by meteorfox** [comment]
:+1: Looking forward to this feature. Let me know if I can help with anything.

**Comment by mtrofimm** [comment]
:+1:
